openapi: 3.0.1
info:
  title: Travel Social Network API
  version: 1.0.3
servers:
  - url: https://api.example.com
security:
  - bearerAuth: []

tags:
  - name: Places
  - name: Posts
  - name: Reactions
  - name: Comments
  - name: Uploads

paths:
  /places:
    get:
      tags: [Places]
      summary: Список мест
      description: >
        Список мест с курсорной пагинацией и поиском по названию.
      security: []
      parameters:
        - $ref: '#/components/parameters/q'
        - $ref: '#/components/parameters/sort'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/after'
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceListResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '500': { $ref: '#/components/responses/InternalServerError' }

  /posts:
    get:
      tags: [Posts]
      summary: Список постов
      parameters:
        - $ref: '#/components/parameters/author_id'
        - $ref: '#/components/parameters/place_id'
        - $ref: '#/components/parameters/feed'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/after'
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostListResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '500': { $ref: '#/components/responses/InternalServerError' }
    post:
      tags: [Posts]
      summary: Создать пост
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/PostCreateRequest' }
      responses:
        '201':
          description: Создано
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Post' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalServerError' }

  /posts/{post_id}/comments:
    get:
      tags: [Comments]
      summary: Комментарии к посту
      parameters:
        - name: post_id
          in: path
          required: true
          schema: { $ref: '#/components/schemas/UUID' }
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/after'
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema: { $ref: '#/components/schemas/CommentListResponse' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '404': { $ref: '#/components/responses/NotFound' }
        '500': { $ref: '#/components/responses/InternalServerError' }
    post:
      tags: [Comments]
      summary: Добавить комментарий
      parameters:
        - name: post_id
          in: path
          required: true
          schema: { $ref: '#/components/schemas/UUID' }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CommentCreateRequest' }
      responses:
        '201':
          description: Создано
          content:
            application/json:
              schema: { $ref: '#/components/schemas/CommentItem' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '404': { $ref: '#/components/responses/NotFound' }
        '500': { $ref: '#/components/responses/InternalServerError' }

  /posts/{post_id}/likes:
    get:
      tags: [Reactions]
      summary: Лайки поста
      parameters:
        - name: post_id
          in: path
          required: true
          schema: { $ref: '#/components/schemas/UUID' }
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/after'
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema: { $ref: '#/components/schemas/LikeListResponse' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '404': { $ref: '#/components/responses/NotFound' }
        '500': { $ref: '#/components/responses/InternalServerError' }
    post:
      tags: [Reactions]
      summary: Поставить лайк посту
      parameters:
        - name: post_id
          in: path
          required: true
          schema: { $ref: '#/components/schemas/UUID' }
      responses:
        '204': { description: Лайк установлен }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '404': { $ref: '#/components/responses/NotFound' }
        '409':
          description: Уже лайкнуто
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '500': { $ref: '#/components/responses/InternalServerError' }

  /uploads/images:
    post:
      tags: [Uploads]
      summary: Загрузка изображения
      description: Вернёт URL для прямой загрузки и ключ объекта; в POST /posts передаётся storage_key.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadImageRequest'
      responses:
        '201':
          description: ОК
          content:
            application/json:
              schema: { $ref: '#/components/schemas/UploadInitResponse' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalServerError' }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    limit:
      name: limit
      in: query
      schema: { type: integer, minimum: 1, maximum: 100, default: 50 }
      description: Размер страницы
    after:
      name: after
      in: query
      schema: { type: string }
      description: Курсор следующей страницы
    q:
      name: q
      in: query
      schema: { type: string }
      description: Поиск по названию места (подстрока)
    author_id:
      name: author_id
      in: query
      schema: { $ref: '#/components/schemas/UUID' }
      description: Фильтр постов по автору
    place_id:
      name: place_id
      in: query
      schema: { $ref: '#/components/schemas/UUID' }
      description: Фильтр постов, привязанных к месту
    feed:
      name: feed
      in: query
      schema:
        type: string
        enum: [all, following]
        default: all
      description: Тип ленты постов (all - все посты, following - лента подписок)
    sort:
      name: sort
      in: query
      schema:
        type: string
        enum: [default, popular]
        default: default
      description: Сортировка мест (default - по умолчанию, popular - популярные)

  responses:
    BadRequest:
      description: Некорректный запрос
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
    Unauthorized:
      description: Требуется аутентификация
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
    InternalServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }

  schemas:
    UUID:
      type: string
      format: uuid
      example: "6a7a3b12-6a9c-4e35-9f3b-4e6e8f4c9d21"
    ISODateTime:
      type: string
      format: date-time
      example: "2025-10-15T14:03:27Z"
    PageMeta:
      type: object
      required: [limit]
      properties:
        limit: { type: integer, example: 50 }
        next_after:
          type: string
          nullable: true
          example: "eyJvZmZzZXQiOjE3MDEyMzQ1Nn0="
    Error:
      type: object
      required: [code, message]
      properties:
        code: { type: string, example: bad_request }
        message: { type: string, example: Invalid parameter 'limit' }

    UserPublic:
      type: object
      required: [id, username, name]
      properties:
        id: { $ref: '#/components/schemas/UUID' }
        username: { type: string, example: "ivan_petrov" }
        name: { type: string, example: "Ivan Petrov" }
        avatar_url:
          type: string
          format: uri
          nullable: true
        status:
          type: string
          nullable: true

    PlaceItem:
      type: object
      required: [id, name]
      properties:
        id: { $ref: '#/components/schemas/UUID' }
        name: { type: string, example: "Красная площадь" }
        location:
          type: object
          nullable: true
          description: Геометка (latitude, longitude)
          properties:
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float
        country_code:
          type: string
          nullable: true
        admin_area:
          type: string
          nullable: true
        posts_count:
          type: integer
          nullable: true
        popularity_score:
          type: number
          nullable: true
    PlaceListResponse:
      type: object
      required: [items, page]
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/PlaceItem' }
        page: { $ref: '#/components/schemas/PageMeta' }

    ImageRef:
      type: object
      required: [url]
      properties:
        url:
          type: string
          format: uri
          description: URL
        etag:
          type: string
          nullable: true
          description: Версия/ETag для кэшей.
    Post:
      type: object
      required: [id, author, description, created_at, updated_at]
      properties:
        id: { $ref: '#/components/schemas/UUID' }
        author: { $ref: '#/components/schemas/UserPublic' }
        description: { type: string, maxLength: 10000 }
        places:
          type: array
          items: { $ref: '#/components/schemas/PlaceItem' }
        images:
          type: array
          maxItems: 10
          items: { $ref: '#/components/schemas/ImageRef' }
        likes_count: { type: integer, example: 57 }
        comments_count: { type: integer, example: 13 }
        created_at: { $ref: '#/components/schemas/ISODateTime' }
        updated_at: { $ref: '#/components/schemas/ISODateTime' }
    PostListResponse:
      type: object
      required: [items, page]
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/Post' }
        page: { $ref: '#/components/schemas/PageMeta' }
    PostCreateRequest:
      type: object
      required: [description]
      properties:
        description: { type: string, maxLength: 10000 }
        place_ids:
          type: array
          items: { $ref: '#/components/schemas/UUID' }
        images:
          type: array
          description: Предварительно загруженные изображения.
          items:
            type: object
            required: [storage_key]
            properties:
              storage_key:
                type: string
                description: Ключ в объектном хранилище

    CommentCreateRequest:
      type: object
      required: [body]
      properties:
        parent_id:
          type: string
          format: uuid
          nullable: true
        body: { type: string, maxLength: 10000 }

    CommentItem:
      type: object
      required: [id, post_id, user, body, created_at]
      properties:
        id: { $ref: '#/components/schemas/UUID' }
        post_id: { $ref: '#/components/schemas/UUID' }
        user: { $ref: '#/components/schemas/UserPublic' }
        body: { type: string }
        parent_id:
          type: string
          format: uuid
          nullable: true
        created_at: { $ref: '#/components/schemas/ISODateTime' }
    CommentListResponse:
      type: object
      required: [items, page]
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/CommentItem' }
        page: { $ref: '#/components/schemas/PageMeta' }

    LikeItem:
      type: object
      required: [user, created_at]
      properties:
        user: { $ref: '#/components/schemas/UserPublic' }
        created_at: { $ref: '#/components/schemas/ISODateTime' }
    LikeListResponse:
      type: object
      required: [items, page]
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/LikeItem' }
        page: { $ref: '#/components/schemas/PageMeta' }

    UploadImageRequest:
      type: object
      required: [content_type, size_bytes]
      properties:
        content_type:
          type: string
          example: image/jpeg
        size_bytes:
          type: integer
        path_hint:
          type: string
          description: Опционально — желаемый префикс пути
    UploadInitResponse:
      type: object
      required: [storage_key, upload_url, expires_at]
      properties:
        storage_key:
          type: string
        upload_url:
          type: string
          format: uri
        expires_at:
          type: string
          format: date-time
